### ISSUE TITLE
Identidade visual GeekIF grupo I

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/geekif.fabsoftware.itp.ifsp.edu.br#1]
- Criação da identidade visual:
    - Paleta de cores
    - Logotipo
    - Fontes
    - Design inicial (landing page)

A Landing page precisa contemplar no mínimo os pontos abaixo:
  - Menu com as páginas do site
  - Sobre o evento
  - Fotos do ano anterior
  - Mapa do evento
  - Contato
    
A Identidade visual precisa estar alinhada com os pontos abaixo:
  - Ainda não definido
  - Roxo/Azul
  - Neon Rosa/Azul/Amarelo/Verde
  - Logo do IF precisa estar no site
  - Redes sociais apontando para as redes do IF

Entrega:
    -  2 identidades visuais

**Comment by gabs1m** [comment]
https://www.figma.com/proto/rwiPmAFg9yaQzVDpmsvoB8/Prot%C3%B3tipo-Gab%2FJP?type=design&node-id=4-2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=4%3A2
